export const cafechairsdata = [
    {				
        "id":	"983",		
        "ModelNo":	"RSC - 983",		
        "Name":	"Tolex with Handle",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc983.jpg"		
    },				
    {				
        "id":	"984",		
        "ModelNo":	"RSC - 984",		
        "Name":	"Tolex without Handle",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc984.jpg"		
    },				
    {				
        "id":	"985",		
        "ModelNo":	"RSC - 985",		
        "Name":	"Tolex Stool",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc985.jpg"		
    },				
    {				
        "id":	"986",		
        "ModelNo":	"RSC - 986",		
        "Name":	"Lara Fix Shell",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc986.jpg"		
    },				
    {				
        "id":	"987",		
        "ModelNo":	"RSC - 987",		
        "Name":	"Lara Wooden Frame",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc987.jpg"		
    },				
    {				
        "id":	"988",		
        "ModelNo":	"RSC - 988",		
        "Name":	"Lara Revolving",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc988.jpg"		
    },				
    {				
        "id":	"989",		
        "ModelNo":	"RSC - 989",		
        "Name":	"Excel with Cousion",		
        "Type":	"Cafeteria Chair",		
        "Fabric":	"Leatherite Upholstery",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc989.jpg"		
    },				
    {				
        "id":	"990",		
        "ModelNo":	"RSC - 990",		
        "Name":	"Excel with Cousion",		
        "Type":	"Cafeteria Chair",		
        "Fabric":	"Leatherite Upholstery",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc990.jpg"		
    },				
    {				
        "id":	"991",		
        "ModelNo":	"RSC - 991",		
        "Name":	"Excel without Cousion",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc991.jpg"		
    },				
    {				
        "id":	"992",		
        "ModelNo":	"RSC - 992",		
        "Name":	"Excel without Cousion",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"PP",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc992.jpg"		
    },				
    {				
        "id":	"995",		
        "ModelNo":	"RSC - 995",		
        "Name":	"Novella",		
        "Type":	"Cafeteria Chair",		
        "FrameMaterial":	"Chrome Frame",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc992.jpg"		
    },				
    {				
        "id":	"974",		
        "ModelNo":	"RSC - 974",		
        "Name":	"Wave Shell",		
        "Type":	"Cafeteria Chair",		
        "Fabric":	"Leatherite Upholstery",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc974.jpg"		
    },				
    {				
        "id":	"975",		
        "ModelNo":	"RSC - 975",		
        "Name":	"Wave Shell",		
        "Mechanism":	"Round Fix Mechanism",		
        "Fabric":	"Leatherite Upholstery",		
        "BaseMaterial":	"Chrome Round Fix Base",		
        "HeightAdjuster":	"Gas Lift",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc975.jpg"		
    },				
    {				
        "id":	"976",		
        "ModelNo":	"RSC - 976",		
        "Name":	"Wave Shell",		
        "Mechanism":	"Round Fix Mechanism",		
        "Fabric":	"Leatherite Upholstery",		
        "BaseMaterial":	"Chrome Base",		
        "HeightAdjuster":	"Gas Lift",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc976.jpg"		
    },				
    {				
        "id":	"964",		
        "ModelNo":	"RSC - 964",		
        "Name":	"Classic Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc964.png"		
    },				
    {				
        "id":	"965",		
        "ModelNo":	"RSC - 965",		
        "Name":	"Classic Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Black Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc965.png"		
    },				
    {				
        "id":	"977",		
        "ModelNo":	"RSC - 977",		
        "Name":	"Classic Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"Chrome Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc977.png"		
    },				
    {				
        "id":	"939",		
        "ModelNo":	"RSC - 939",		
        "Name":	"Football Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc939.png"		
    },				
    {				
        "id":	"940",		
        "ModelNo":	"RSC - 940",		
        "Name":	"Football Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Black Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc940.png"		
    },				
    {				
        "id":	"941",		
        "ModelNo":	"RSC - 941",		
        "Name":	"Jasmy Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc941.png"		
    },				
    {				
        "id":	"942",		
        "ModelNo":	"RSC - 942",		
        "Name":	"Jasmy Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Black Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc942.png"		
    },				
    {				
        "id":	"935",		
        "ModelNo":	"RSC - 935",		
        "Name":	"Jasmy Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"Chrome Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc935.png"		
    },				
    {				
        "id":	"980",		
        "ModelNo":	"RSC - 980",		
        "Name":	"Diamond Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc980.png"		
    },				
    {				
        "id":	"981",		
        "ModelNo":	"RSC - 981",		
        "Name":	"Diamond Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Black Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc981.png"		
    },				
    {				
        "id":	"982",		
        "ModelNo":	"RSC - 982",		
        "Name":	"Diamond Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"Chrome Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc982.png"		
    },				
    {				
        "id":	"936",		
        "ModelNo":	"RSC - 936",		
        "Name":	"Matic Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"PP Colour Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc936.png"		
    },				
    {				
        "id":	"937",		
        "ModelNo":	"RSC - 937",		
        "Name":	"Matic Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Fabric":	"Leatherite Upholstery",		
        "FrameMaterial":	"PP Black Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc937.png"		
    },				
    {				
        "id":	"928",		
        "ModelNo":	"RSC - 928",		
        "Name":	"Matic Shell",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Mechanism":	"Round Fix Mechanism",		
        "Fabric":	"Leatherite Upholstery",		
        "BaseMaterial":	"Chrome Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc928.png"		
    },				
    {				
        "id":	"952",		
        "ModelNo":	"RSC - 952",		
        "Name":	"Matic Shell",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Fabric":	"Leatherite Upholstery",		
        "BaseMaterial":	"Wooden Frame",		
        "Url":	"/images/rsc952.png"		
    },				
    {				
        "id":	"953",		
        "ModelNo":	"RSC - 953",		
        "Name":	"Matic Shell",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Mechanism":	"Round Fix Mechanism",		
        "Fabric":	"Leatherite Upholstery",		
        "BaseMaterial":	"Chrome Round Fix Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc953.png"		
    },				
    {				
        "id":	"923",		
        "ModelNo":	"RSC - 923",		
        "Name":	"Dollar Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"Chrome Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc923.png"		
    },				
    {				
        "id":	"934",		
        "ModelNo":	"RSC - 934",		
        "Name":	"Meghna Shell",		
        "Type":	"Cafeteria Chair",		
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "FrameMaterial":	"Chrome Stand",		
        "HeightAdjuster": "Fixed Height",
        "Url":	"/images/rsc934.png"		
    },				
    {				
        "id":	"845(B)",		
        "ModelNo":	"RSC - 845(B)",		
        "Name":	"Orbit Visitor Mesh",		
        "Type":	"Visitor",		
        "BodyColor":	"Black",		
        "Fabric":	"Net Upholstery",		
        "FrameMaterial":	"Metal Powder Coated Frame",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc845b.png"		
    },				
    {				
        "id":	"845(G)",		
        "ModelNo":	"RSC - 845(G)",		
        "Name":	"Orbit Visitor Mesh",		
        "Type":	"Visitor",		
        "BodyColor":	"Grey",		
        "Fabric":	"Net Upholstery",		
        "FrameMaterial":	"Metel Chrome Frame",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc845g.png"		
    },				
    {				
        "id":	"845(W)",		
        "ModelNo":	"RSC - 845(W)",		
        "Name":	"Orbit Visitor Mesh",		
        "Type":	"Visitor",		
        "BodyColor":	"White",		
        "Fabric":	"Net Upholstery",		
        "FrameMaterial":	"Metel Chrome Frame",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc845w.png"		
    },				
    {				
        "id":	"804",		
        "ModelNo":	"RSC - 804",		
        "Name":	"Emerald",		
        "Type":	"Visitor",		
        "BodyColor":	"Black",		
        "Fabric":	"Fabric Upholstery",		
        "FrameMaterial":	"Metel Chrome Frame",		
        "HeightAdjuster": "Fixed Height",
        "ColorOptions":	"<span className='flex space-x-2'><code class='w-4 h-4 bg-gray-700 rounded'></code><code class='w-4 h-4 bg-blue-600 rounded'></code><code class='w-4 h-4 bg-green-500 rounded'></code><code class='w-4 h-4 bg-red-500 rounded'></code><code class='w-4 h-4 bg-orange-500 rounded'></code><code class='w-4 h-4 bg-yellow-300 rounded'></code><code class='w-4 h-4 bg-teal-500 rounded'></code></span>",		
        "Url":	"/images/rsc804.jpg"		
    },				
]