export const workstationchairdata = [
    {				
        "id":	"501(B)",		
        "ModelNo":	"RSC - 501(B)",		
        "Name":	"Joy",		
        "Type":	"Medium Back",		
        "BodyColor":	"Black",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc501b.jpg"		
    },				
    {				
        "id":	"501(G)",		
        "ModelNo":	"RSC - 501(G)",		
        "Name":	"Joy",		
        "Type":	"Medium Back",		
        "BodyColor":	"Grey",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"Adjustable PU Handle with PU Pad",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc501g.jpg"		
    },				
    {				
        "id":	"501(W)",		
        "ModelNo":	"RSC - 501(W)",		
        "Name":	"Joy",		
        "Type":	"Medium Back",		
        "BodyColor":	"White",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc501w.jpg"		
    },				
    {				
        "id":	"502(B)",		
        "ModelNo":	"RSC - 502(B)",		
        "Name":	"Century",		
        "Type":	"Medium Back",		
        "BodyColor":	"Black",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc502b.jpg"		
    },				
    {				
        "id":	"502(G)",		
        "ModelNo":	"RSC - 502(G)",		
        "Name":	"Century",		
        "Type":	"Medium Back",		
        "BodyColor":	"Grey",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc502g.jpg"		
    },				
    {				
        "id":	"502(W)",		
        "ModelNo":	"RSC - 502(W)",		
        "Name":	"Century",		
        "Type":	"Medium Back",		
        "BodyColor":	"White",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc502w.jpg"		
    },				
    {				
        "id":	"504(B)",		
        "ModelNo":	"RSC - 504(B)",		
        "Name":	"Ruby High Back",		
        "Type":	"Medium Back",		
        "BodyColor":	"Black",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc504b.jpg"		
    },				
    {				
        "id":	"504(G)",		
        "ModelNo":	"RSC - 504(G)",		
        "Name":	"Ruby High Back",		
        "Type":	"Medium Back",		
        "BodyColor":	"Grey",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc504g.jpg"		
    },				
    {				
        "id":	"504(W)",		
        "ModelNo":	"RSC - 504(W)",		
        "Name":	"Ruby High Back",		
        "Type":	"Medium Back",		
        "BodyColor":	"White",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc504w.jpg"		
    },				
    {				
        "id":	"505(B)",		
        "ModelNo":	"RSC - 505(B)",		
        "Name":	"Ruby Low Back",		
        "Type":	"Low Back",		
        "BodyColor":	"Black",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc505b.png"		
    },				
    {				
        "id":	"505(G)",		
        "ModelNo":	"RSC - 505(G)",		
        "Name":	"Ruby Low Back",		
        "Type":	"Low Back",		
        "BodyColor":	"Grey",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc505g.jpg"		
    },				
    {				
        "id":	"505(W)",		
        "ModelNo":	"RSC - 505(W)",		
        "Name":	"Ruby Low Back",		
        "Type":	"Low Back",		
        "BodyColor":	"White",		
        "Mechanism":	"Push Back Mechanism",		
        "Armrest":	"PP Arms",		
        "Fabric":	"Fabric Upholstery",		
        "BaseMaterial":	"Nylone Base",		
        "HeightAdjuster":	"Gas Lift",		
        "Url":	"/images/rsc505w.jpg"		
    }				
]